[package]
name = "tinyraytracer_rs"
version = "0.0.0"
description = "Rust implementation of Tiny Raytracer"
authors = ["Emmanuel Bustos <ema2159@gmail.com>"]

[dependencies]
image = "0.24.5"
piston_window = "0.127.0"
nalgebra = "0.31.4"
